# Generated by Django 3.1.13 on 2021-10-30 11:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plants', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='plant',
            name='grow_days',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
